sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_TRAVISCI=phpstan
    - php: 7.2
      env: WP_TRAVISCI=psalm
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
  - export VENDOR="$HOME/.composer/vendor"
  - export PATH="$VENDOR/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require --dev dealerdirect/phpcodesniffer-composer-installer:^0.6 phpcompatibility/phpcompatibility-wp:* wp-coding-standards/wpcs:* automattic/vipwpcs:*
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpstan" ]] ; then
      composer global require --dev phpstan/phpstan:* szepeviktor/phpstan-wordpress:*
    fi
  - |
    if [[ "$WP_TRAVISCI" == "psalm" ]] ; then
      composer global require --dev vimeo/psalm:* humanmade/psalm-plugin-wordpress:*
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpstan" ]] ; then
      phpstan analyze
    fi
  - |
    if [[ "$WP_TRAVISCI" == "psalm" ]] ; then
      psalm --stats --debug-by-line
    fi
