name: cd

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'
          coverage: none
          tools: composer:v1
      - run: svn checkout https://plugins.svn.wordpress.org/player-for-web-pure-data-patches
      - run: composer install -d public/wp-content/plugins/player-for-web-pure-data-patches --prefer-dist --classmap-authoritative --no-progress --no-interaction --no-dev
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn start
      - run: zip -r player-for-web-pure-data-patches.zip dist inc vendor composer.json LICENSE README.md player-for-web-pure-data-patches.php
      - run: cd player-for-web-pure-data-patches && rm -rf trunk/*
      - run: cd player-for-web-pure-data-patches && svn st | grep ! | cut -d! -f2| sed 's/^ *//' | sed 's/^/"/g' | sed 's/$/"/g' | xargs svn rm
      - run: cd player-for-web-pure-data-patches && svn add `svn status | grep ?`
      - run: unzip player-for-web-pure-data-patches.zip -d player-for-web-pure-data-patches/trunk
      - run: mv player-for-web-pure-data-patches/trunk/README.md player-for-web-pure-data-patches/trunk/README.txt
      - run: TAG=`grep -Po '\d*\.\d*\.\d*' player-for-web-pure-data-patches.php 
      - run: cd player-for-web-pure-data-patches && svn copy trunk tags/$TAG
      - run: cd player-for-web-pure-data-patches && svn commit -m "New version $TAG" --username=opengeekv2 --password=$WORDPRES_PLUGIN_DIRTECTORY_PASS
        env:
          WORDPRES_PLUGIN_DIRTECTORY_PASS: ${{ secrets.WORDPRES_PLUGIN_DIRTECTORY_PASS }}


