name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_to_fail }}
    strategy:
      matrix:
        php: ['5.6']
        wp-version: ['trunk']
        allowed_to_fail: [false]
        include:
          - php: '5.6'
            wp-version: latest
            allowed_to_fail: false
          - php: '7.0'
            wp-version: latest
            allowed_to_fail: false
          - php: '7.1'
            wp-version: latest
            allowed_to_fail: false
          - php: '7.2'
            wp-version: latest
            allowed_to_fail: false
          - php: '7.3'
            wp-version: latest
            allowed_to_fail: false
          - php: '7.4'
            wp-version: latest
            allowed_to_fail: false
          - php: '8.0'
            wp-version: latest
            allowed_to_fail: false
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v1
      - run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1:${{ job.services.mysql.ports['3306'] }} ${{ matrix.wp-version }} true
      - run: composer global require "phpunit/phpunit=4.8.*|5.7.*"
      - if: ${{ matrix.php == '7.2' || matrix.php == '7.3' || matrix.php == '7.4' || matrix.php == '8.0' }}
        run: composer install
      - if: ${{ matrix.php == '5.6' || matrix.php == '7.0' || matrix.php == '7.1' }}
        run: composer install --no-dev
      - run: phpunit --coverage-clover=clover.xml
      - run: WP_MULTISITE=1 phpunit --coverage-clover=clover.xml
      - uses: codecov/codecov-action@v1
