name: qa

on:
  push:
    branches: [master, development]
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_to_fail }}
    strategy:
      matrix:
        php: ['5.6', '7.2']
        allowed_to_fail: [false]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v1
      - run: export VENDOR="$HOME/.composer/vendor"
      - run: export PATH="$VENDOR/bin:$PATH"
      - if: ${{ matrix.php == '5.6' }}
        run: composer global require --dev dealerdirect/phpcodesniffer-composer-installer:^0.6 phpcompatibility/phpcompatibility-wp:* wp-coding-standards/wpcs:* automattic/vipwpcs:*
      - if: ${{ matrix.php == '5.6' }}
        run: phpcs
      - if: ${{ matrix.php == '7.2' }}
        run: composer global require --dev phpstan/phpstan:* phpstan/extension-installer szepeviktor/phpstan-wordpress:* vimeo/psalm:* humanmade/psalm-plugin-wordpress:*
      - if: ${{ matrix.php == '7.2' }}
        run: composer install
      - if: ${{ matrix.php == '7.2' }}
        run: sed "s+vendor/szepeviktor/phpstan-wordpress/extension.neon+$VENDOR/szepeviktor/phpstan-wordpress/extension.neon+g" phpstan.neon.dist
      - if: ${{ matrix.php == '7.2' }}
        run: phpstan analyze
      - if: ${{ matrix.php == '7.2' }}
        run: psalm --stats
